//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netMvcTest.Model.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _202002031153291_init {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _202002031153291_init() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("netMvcTest.Model.Migrations.202002031153291_init", typeof(_202002031153291_init).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEAO1cWW/cNhB+L9D/IOipLZyVjz60xm6CZB0HRuMD3k3QN4OWuGuiErWRKHcXRX9ZH/qT+hdKrS6euveKgwCBTZHD4fCb4Qw54//++Xf4Zum5xjMMQuTjkXkyODYNiG3fQXg+MiMye/WL+eb1998N3zve0vic9TuL+9GROByZT4Qszi0rtJ+gB8KBh+zAD/0ZGdi+ZwHHt06Pj3+1Tk4sSEmYlJZhDO8jTJAH17/QX8c+tuGCRMC99h3ohmk7/TJZUzVugAfDBbDhyMSQXD/bUxiSwbrz4D0lRVam8dZFgLIzge7MNADGPgGEMnv+KYQTEvh4PlnQBuBOVwtI+82AG8J0EedF97rrOT6N12MVAzNSdhQS32tI8OQsFZAlDm8lZjMXIBVhIp941Wsxjsy3AUG2S9cuznU+doO4n1bIg3TokSF2OMqxQSEU/zsyxpFLogCOMIxIAGiPu+jRRfZvcDX1/4B4hCPXZRmlrNJvXANtugv8BQzI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
